const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM_FROM_CART: "DELETE_ITEM_FROM_CART",
  ADD_ONE_TO_CART: "ADD_ONE_TO_CART",
  SUBSTRACT_ONE_TO_CART: "SUBSTRACT_ONE_TO_CART",
};

export default CartActionTypes;
